services:
  backend:
    image: ghcr.io/vs-uulm/prepams/backend
    restart: unless-stopped
    volumes:
      - ./backend_env:/prepams/backend/.env
      - ./backend_data:/prepams/backend/data
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.api.rule=Host(`${PREPAMS_HOST}`) && PathPrefix(`/api/`)"
      - "traefik.http.routers.api.service=api"
      - "traefik.http.services.api.loadbalancer.server.port=8080"
      - "traefik.http.routers.api.entrypoints=websecure"
      - "traefik.http.routers.api.tls.certresolver=myresolver"
      - "traefik.http.routers.eval.rule=Host(`${PREPAMS_HOST}`) && PathPrefix(`/post`)"
      - "traefik.http.routers.eval.service=eval"
      - "traefik.http.services.eval.loadbalancer.server.port=52716"
      - "traefik.http.routers.eval.entrypoints=websecure"
      - "traefik.http.routers.eval.tls.certresolver=myresolver"

  frontend:
    image: ghcr.io/vs-uulm/prepams/frontend
    restart: unless-stopped
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.ui.rule=Host(`${PREPAMS_HOST}`)"
      - "traefik.http.routers.ui.entrypoints=websecure"
      - "traefik.http.routers.ui.tls.certresolver=myresolver"

  survey:
    image: ghcr.io/vs-uulm/prepams/survey
    restart: unless-stopped
    volumes:
      - ./survey_env:/prepams/survey/.env
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.survey.rule=Host(`${SURVEY_HOST}`)"
      - "traefik.http.routers.survey.entrypoints=websecure"
      - "traefik.http.routers.survey.tls.certresolver=myresolver"

  traefik:
    image: "traefik:v2.4"
    restart: unless-stopped
    command:
      - "--providers.docker=true"
      - "--providers.docker.exposedbydefault=false"
      - "--entrypoints.websecure.address=:443"
      - "--certificatesresolvers.myresolver.acme.tlschallenge=true"
      - "--certificatesresolvers.myresolver.acme.email=${ACME_EMAIL}"
      - "--certificatesresolvers.myresolver.acme.storage=/letsencrypt/acme.json"
    ports:
      - "443:443"
      - "80:80"
    volumes:
      - "/var/run/docker.sock:/var/run/docker.sock:ro"  
      - "./letsencrypt:/letsencrypt"

